using APIHealthMonitoring.Domain.Enums;

namespace APIHealthMonitoring.Domain.Entities;

/// <summary>
/// Represents an alert generated when a monitored API endpoint breaches a threshold.
/// Lifecycle: Open → Closed (by auto-recovery or manual resolution).
/// Alerts are created only by the Health Check Engine — never by users.
/// </summary>
public class Alert : BaseEntity
{
    // -------------------------------------------------------------------------
    // FK & Navigation
    // -------------------------------------------------------------------------

    /// <summary>The endpoint this alert was generated for.</summary>
    public int ApiEndpointId { get; set; }

    /// <summary>Navigation back to the parent endpoint.</summary>
    public ApiEndpoint? ApiEndpoint { get; set; }

    // -------------------------------------------------------------------------
    // Alert Data
    // -------------------------------------------------------------------------

    /// <summary>Severity level: Warning or Critical.</summary>
    public AlertSeverity Severity { get; set; }

    /// <summary>Human-readable description of the alert condition.</summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>UTC timestamp when the alert was generated by the system.</summary>
    public DateTime GeneratedAt { get; set; }

    /// <summary>UTC timestamp when the alert was resolved. Null while still Open.</summary>
    public DateTime? ResolvedAt { get; set; }

    /// <summary>Current lifecycle status: Open or Closed.</summary>
    public AlertStatus Status { get; set; } = AlertStatus.Open;
}
