<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\APIHealthMonitoring.Application\APIHealthMonitoring.Application.csproj" />
    <ProjectReference Include="..\APIHealthMonitoring.Domain\APIHealthMonitoring.Domain.csproj" />
    <ProjectReference Include="..\APIHealthMonitoring.Persistence\APIHealthMonitoring.Persistence.csproj" />
  </ItemGroup>

</Project>
